const MillionaireQuestions = [
  [
    {
      id: 1,
      question: "Thủ đô của Việt Nam là gì?",
      options: ["Hà Nội", "TP. Hồ Chí Minh", "Đà Nẵng", "Huế"],
      answer: "Hà Nội",
    },
    {
      id: 2,
      question: "Người phát minh ra bóng đèn điện là ai?",
      options: [
        "Thomas Edison",
        "Albert Einstein",
        "Isaac Newton",
        "Nikola Tesla",
      ],
      answer: "Thomas Edison",
    },
    {
      id: 3,
      question: "Quốc gia nào có diện tích lớn nhất thế giới?",
      options: ["Canada", "Trung Quốc", "Nga", "Mỹ"],
      answer: "Nga",
    },
    {
      id: 4,
      question: "Hành tinh nào gần Mặt Trời nhất?",
      options: ["Trái Đất", "Sao Kim", "Sao Thủy", "Sao Hỏa"],
      answer: "Sao Thủy",
    },
    {
      id: 5,
      question: "Ngôn ngữ chính thức của Brazil là gì?",
      options: ["Tây Ban Nha", "Bồ Đào Nha", "Anh", "Pháp"],
      answer: "Bồ Đào Nha",
    },
    {
      id: 6,
      question: "Ai là tác giả của truyện Kiều?",
      options: ["Nguyễn Trãi", "Nguyễn Du", "Hồ Xuân Hương", "Tản Đà"],
      answer: "Nguyễn Du",
    },
    {
      id: 7,
      question: "Đơn vị đo cường độ dòng điện là gì?",
      options: ["Volt", "Ohm", "Ampere", "Watt"],
      answer: "Ampere",
    },
    {
      id: 8,
      question: "Thành phần chính của không khí là gì?",
      options: ["Oxy", "Carbon Dioxide", "Nitơ", "Hydro"],
      answer: "Nitơ",
    },
    {
      id: 9,
      question: "Quốc gia nào nổi tiếng với kim tự tháp?",
      options: ["Mexico", "Ấn Độ", "Ai Cập", "Trung Quốc"],
      answer: "Ai Cập",
    },
    {
      id: 10,
      question: "Một năm nhuận có bao nhiêu ngày?",
      options: ["365", "366", "364", "367"],
      answer: "366",
    },
    {
      id: 11,
      question: "Người đầu tiên đặt chân lên Mặt Trăng là ai?",
      options: [
        "Buzz Aldrin",
        "Yuri Gagarin",
        "Neil Armstrong",
        "Michael Collins",
      ],
      answer: "Neil Armstrong",
    },
    {
      id: 12,
      question: "Tổng thống đầu tiên của nước Mỹ là ai?",
      options: [
        "George Washington",
        "Abraham Lincoln",
        "John Adams",
        "Thomas Jefferson",
      ],
      answer: "George Washington",
    },
    {
      id: 13,
      question: "Sông nào dài nhất thế giới?",
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      answer: "Nile",
    },
    {
      id: 14,
      question: "Thành phố nào được mệnh danh là 'Thành phố ngàn hoa'?",
      options: ["Đà Lạt", "Huế", "Hà Nội", "TP. Hồ Chí Minh"],
      answer: "Đà Lạt",
    },
    {
      id: 15,
      question: "Tác phẩm 'Harry Potter' do ai sáng tác?",
      options: [
        "J.K. Rowling",
        "Suzanne Collins",
        "Stephen King",
        "George R.R. Martin",
      ],
      answer: "J.K. Rowling",
    },
  ],
  // Bộ thứ hai (sẽ shuffle lại và id cũng từ 1-15)
  [
    {
      id: 1,
      question: "Tổng thống đầu tiên của nước Mỹ là ai?",
      options: [
        "George Washington",
        "Abraham Lincoln",
        "John Adams",
        "Thomas Jefferson",
      ],
      answer: "George Washington",
    },
    {
      id: 2,
      question: "Ngôn ngữ chính thức của Brazil là gì?",
      options: ["Tây Ban Nha", "Bồ Đào Nha", "Anh", "Pháp"],
      answer: "Bồ Đào Nha",
    },
    {
      id: 3,
      question: "Một năm nhuận có bao nhiêu ngày?",
      options: ["365", "366", "364", "367"],
      answer: "366",
    },
    {
      id: 4,
      question: "Ai là tác giả của truyện Kiều?",
      options: ["Nguyễn Trãi", "Nguyễn Du", "Hồ Xuân Hương", "Tản Đà"],
      answer: "Nguyễn Du",
    },
    {
      id: 5,
      question: "Hành tinh nào gần Mặt Trời nhất?",
      options: ["Trái Đất", "Sao Kim", "Sao Thủy", "Sao Hỏa"],
      answer: "Sao Thủy",
    },
    {
      id: 6,
      question: "Sông nào dài nhất thế giới?",
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      answer: "Nile",
    },
    {
      id: 7,
      question: "Thành phố nào được mệnh danh là 'Thành phố ngàn hoa'?",
      options: ["Đà Lạt", "Huế", "Hà Nội", "TP. Hồ Chí Minh"],
      answer: "Đà Lạt",
    },
    {
      id: 8,
      question: "Thành phần chính của không khí là gì?",
      options: ["Oxy", "Carbon Dioxide", "Nitơ", "Hydro"],
      answer: "Nitơ",
    },
    {
      id: 9,
      question: "Thủ đô của Việt Nam là gì?",
      options: ["Hà Nội", "TP. Hồ Chí Minh", "Đà Nẵng", "Huế"],
      answer: "Hà Nội",
    },
    {
      id: 10,
      question: "Quốc gia nào nổi tiếng với kim tự tháp?",
      options: ["Mexico", "Ấn Độ", "Ai Cập", "Trung Quốc"],
      answer: "Ai Cập",
    },
    {
      id: 11,
      question: "Người đầu tiên đặt chân lên Mặt Trăng là ai?",
      options: [
        "Buzz Aldrin",
        "Yuri Gagarin",
        "Neil Armstrong",
        "Michael Collins",
      ],
      answer: "Neil Armstrong",
    },
    {
      id: 12,
      question: "Quốc gia nào có diện tích lớn nhất thế giới?",
      options: ["Canada", "Trung Quốc", "Nga", "Mỹ"],
      answer: "Nga",
    },
    {
      id: 13,
      question: "Người phát minh ra bóng đèn điện là ai?",
      options: [
        "Thomas Edison",
        "Albert Einstein",
        "Isaac Newton",
        "Nikola Tesla",
      ],
      answer: "Thomas Edison",
    },
    {
      id: 14,
      question: "Đơn vị đo cường độ dòng điện là gì?",
      options: ["Volt", "Ohm", "Ampere", "Watt"],
      answer: "Ampere",
    },
    {
      id: 15,
      question: "Tác phẩm 'Harry Potter' do ai sáng tác?",
      options: [
        "J.K. Rowling",
        "Suzanne Collins",
        "Stephen King",
        "George R.R. Martin",
      ],
      answer: "J.K. Rowling",
    },
  ],
  // Bộ thứ ba
  [
    {
      id: 1,
      question: "Người đầu tiên đặt chân lên Mặt Trăng là ai?",
      options: [
        "Buzz Aldrin",
        "Yuri Gagarin",
        "Neil Armstrong",
        "Michael Collins",
      ],
      answer: "Neil Armstrong",
    },
    {
      id: 2,
      question: "Ngôn ngữ chính thức của Brazil là gì?",
      options: ["Tây Ban Nha", "Bồ Đào Nha", "Anh", "Pháp"],
      answer: "Bồ Đào Nha",
    },
    {
      id: 3,
      question: "Sông nào dài nhất thế giới?",
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      answer: "Nile",
    },
    {
      id: 4,
      question: "Người phát minh ra bóng đèn điện là ai?",
      options: [
        "Thomas Edison",
        "Albert Einstein",
        "Isaac Newton",
        "Nikola Tesla",
      ],
      answer: "Thomas Edison",
    },
    {
      id: 5,
      question: "Hành tinh nào gần Mặt Trời nhất?",
      options: ["Trái Đất", "Sao Kim", "Sao Thủy", "Sao Hỏa"],
      answer: "Sao Thủy",
    },
    {
      id: 6,
      question: "Thành phố nào được mệnh danh là 'Thành phố ngàn hoa'?",
      options: ["Đà Lạt", "Huế", "Hà Nội", "TP. Hồ Chí Minh"],
      answer: "Đà Lạt",
    },
    {
      id: 7,
      question: "Tổng thống đầu tiên của nước Mỹ là ai?",
      options: [
        "George Washington",
        "Abraham Lincoln",
        "John Adams",
        "Thomas Jefferson",
      ],
      answer: "George Washington",
    },
    {
      id: 8,
      question: "Ai là tác giả của truyện Kiều?",
      options: ["Nguyễn Trãi", "Nguyễn Du", "Hồ Xuân Hương", "Tản Đà"],
      answer: "Nguyễn Du",
    },
    {
      id: 9,
      question: "Quốc gia nào nổi tiếng với kim tự tháp?",
      options: ["Mexico", "Ấn Độ", "Ai Cập", "Trung Quốc"],
      answer: "Ai Cập",
    },
    {
      id: 10,
      question: "Thành phần chính của không khí là gì?",
      options: ["Oxy", "Carbon Dioxide", "Nitơ", "Hydro"],
      answer: "Nitơ",
    },
    {
      id: 11,
      question: "Đơn vị đo cường độ dòng điện là gì?",
      options: ["Volt", "Ohm", "Ampere", "Watt"],
      answer: "Ampere",
    },
    {
      id: 12,
      question: "Thủ đô của Việt Nam là gì?",
      options: ["Hà Nội", "TP. Hồ Chí Minh", "Đà Nẵng", "Huế"],
      answer: "Hà Nội",
    },
    {
      id: 13,
      question: "Một năm nhuận có bao nhiêu ngày?",
      options: ["365", "366", "364", "367"],
      answer: "366",
    },
    {
      id: 14,
      question: "Tác phẩm 'Harry Potter' do ai sáng tác?",
      options: [
        "J.K. Rowling",
        "Suzanne Collins",
        "Stephen King",
        "George R.R. Martin",
      ],
      answer: "J.K. Rowling",
    },
    {
      id: 15,
      question: "Quốc gia nào có diện tích lớn nhất thế giới?",
      options: ["Canada", "Trung Quốc", "Nga", "Mỹ"],
      answer: "Nga",
    },
  ],
];

export default MillionaireQuestions;
